version: '3.9'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/pat_elo
      CORS_ORIGIN: http://localhost:5173,http://localhost:8080
      ENABLE_API_DOCS: 'false'
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:4000
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  mongo-data:
