name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Run server tests with coverage
        working-directory: server
        env:
          NODE_ENV: test
          SKIP_DB: 'true'
          SKIP_AUTH: 'true'
        run: npm run test:coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: server/coverage/**

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_BASE_URL: http://localhost:4000
        run: npm run build